const mongoose = require("mongoose");

const complaintSchema = new mongoose.Schema(
    {
        // USER WHO CREATED THE COMPLAINT
        user: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
            required: true,
        },

        // BASIC INFO
        title: {
            type: String,
            required: [true, "Please provide a title"],
        },

        description: {
            type: String,
            required: [true, "Please provide a description"],
        },

        // LOCATION DATA
        location: {
            type: String,
            required: [true, "Please provide a location"],
        },
        latitude: { type: Number },
        longitude: { type: Number },

        // CATEGORY (AI or Admin Assigned)
        category: { type: String, default: "Uncategorized" },

        // URGENCY 1–5 (AI or Admin Assigned)
        urgency: { type: Number, default: 1 },

        // SEVERITY FLAGS
        severity: {
            traffic_block: { type: Boolean, default: false },
            water_leak: { type: Boolean, default: false },
            electricity_risk: { type: Boolean, default: false },
            fire_hazard: { type: Boolean, default: false },
        },

        // DEPARTMENT ROUTING
        department: { type: String, default: "General" },

        // COMPLAINT STATUS
        status: {
            type: String,
            enum: ["Pending", "In Progress", "Resolved"],
            default: "Pending",
        },

        // MULTIPLE IMAGES SUPPORT
        images: {
            type: [String], // array of file paths or cloud URLs
            default: [],
        },

        // RESOLUTION DATA
        resolutionNote: { type: String, default: "" },
        userRating: { type: Number, min: 1, max: 5 },

        // LOCATION DETAILS (For Analytics)
        city: { type: String, default: "" },
        area: { type: String, default: "" },

        // SOFT DELETE
        isDeleted: { type: Boolean, default: false },

        // STAFF ASSIGNMENT
        assignedTo: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
            default: null,
        },

        // Prevent user from editing after admin begins work
        isLocked: {
            type: Boolean,
            default: false,
        },

        // ADMIN NOTES
        adminNotes: [
            {
                note: String,
                admin: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
                createdAt: { type: Date, default: Date.now },
            },
        ],

        // TIMELINE FOR DASHBOARD
        timeline: [
            {
                status: String,
                message: String,
                timestamp: { type: Date, default: Date.now },
            },
        ],

        // AI PROCESSING DETAILS
        aiMeta: {
            model: { type: String }, // e.g., "BERT-v2"
            confidence: { type: Number, default: 0 }, // 0–1
            urgencyConfidence: { type: Number, default: 0 }, // 0–1
            autoGenerated: { type: Boolean, default: true },
        },

        createdAt: {
            type: Date,
            default: Date.now,
        },
    },
    { timestamps: true }
);

// Auto-add timeline entry when status changes
complaintSchema.pre("save", function (next) {
    if (this.isModified("status")) {
        this.timeline.push({
            status: this.status,
            message: `Status updated to ${this.status}`,
            timestamp: new Date(),
        });
    }
    next();
});

module.exports = mongoose.model("Complaint", complaintSchema);
